# Generated by Django 5.2.5 on 2026-08-08 00:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('especialidades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('crm', models.CharField(max_length=30, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('valor_consulta', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('duracao_consulta', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(5)])),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicos', to='especialidades.especialidade')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='medico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('nome',),
                'indexes': [models.Index(fields=['nome'], name='medicos_med_nome_091d29_idx'), models.Index(fields=['crm'], name='medicos_med_crm_779aac_idx')],
            },
        ),
    ]
