# Generated by Django 5.2.5 on 2026-08-08 00:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueioAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('motivo', models.CharField(choices=[('FERIAS', 'Férias'), ('FERIADO', 'Feriado'), ('REUNIAO', 'Reunião'), ('COMPROMISSO', 'Compromisso'), ('INDISPONIBILIDADE', 'Indisponibilidade'), ('OUTRO', 'Outro')], max_length=20)),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueios', to='medicos.medico')),
            ],
            options={
                'ordering': ('-data', 'hora_inicio'),
                'indexes': [models.Index(fields=['medico', 'data'], name='agenda_bloq_medico__be7455_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('hora_fim__gt', models.F('hora_inicio'))), name='agenda_bloqueio_horas_validas'), models.UniqueConstraint(fields=('medico', 'data', 'hora_inicio', 'hora_fim'), name='agenda_bloqueio_periodo_unico')],
            },
        ),
        migrations.CreateModel(
            name='DisponibilidadeMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('duracao_consulta', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(5)])),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='medicos.medico')),
            ],
            options={
                'ordering': ('medico__nome', 'dia_semana', 'hora_inicio'),
                'indexes': [models.Index(fields=['medico', 'dia_semana', 'ativo'], name='agenda_disp_medico__0fa826_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('hora_fim__gt', models.F('hora_inicio'))), name='agenda_disponibilidade_horas_validas'), models.UniqueConstraint(fields=('medico', 'dia_semana', 'hora_inicio', 'hora_fim'), name='agenda_disponibilidade_periodo_unico')],
            },
        ),
    ]
