# Generated by Django 5.2.5 on 2026-08-08 00:00

import accounts.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[accounts.validators.validate_cpf])),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('O', 'Outro'), ('N', 'Prefiro não informar')], max_length=1)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('endereco', models.CharField(max_length=180)),
                ('numero', models.CharField(max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2, validators=[accounts.validators.validate_uf])),
                ('cep', models.CharField(max_length=8)),
                ('contato_emergencia', models.CharField(blank=True, max_length=150)),
                ('telefone_emergencia', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='paciente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('nome_completo',),
                'indexes': [models.Index(fields=['nome_completo'], name='pacientes_p_nome_co_d53042_idx'), models.Index(fields=['telefone'], name='pacientes_p_telefon_a9859d_idx')],
            },
        ),
    ]
