# Generated by Django 5.2.5 on 2026-08-08 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultas', '0001_initial'),
        ('medicos', '0001_initial'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescricoes', to='consultas.consulta')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescricoes', to='medicos.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescricoes', to='pacientes.paciente')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ItemPrescricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(max_length=150)),
                ('dosagem', models.CharField(max_length=100)),
                ('frequencia', models.CharField(max_length=100)),
                ('duracao', models.CharField(max_length=100)),
                ('orientacoes', models.TextField(blank=True)),
                ('prescricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='prescricoes.prescricao')),
            ],
        ),
    ]
