# Generated by Django 5.2.5 on 2026-08-08 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultas', '0001_initial'),
        ('medicos', '0001_initial'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queixa_principal', models.TextField()),
                ('sintomas', models.TextField(blank=True)),
                ('historico', models.TextField(blank=True)),
                ('alergias', models.TextField(blank=True)),
                ('antecedentes', models.TextField(blank=True)),
                ('doencas_preexistentes', models.TextField(blank=True)),
                ('medicamentos_em_uso', models.TextField(blank=True)),
                ('historico_familiar', models.TextField(blank=True)),
                ('diagnostico', models.TextField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consulta', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='prontuario', to='consultas.consulta')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prontuarios', to='medicos.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prontuarios', to='pacientes.paciente')),
            ],
            options={
                'ordering': ('-consulta__data', '-consulta__hora_inicio'),
            },
        ),
        migrations.CreateModel(
            name='EvolucaoClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evolucoes', to='medicos.medico')),
                ('prontuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolucoes', to='prontuarios.prontuario')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
