# Generated by Django 5.2.5 on 2026-08-08 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('especialidades', '0001_initial'),
        ('medicos', '0001_initial'),
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('AGENDADA', 'Agendada'), ('CONFIRMADA', 'Confirmada'), ('PACIENTE_CHEGOU', 'Paciente chegou'), ('AGUARDANDO', 'Aguardando'), ('EM_ATENDIMENTO', 'Em atendimento'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada'), ('NAO_COMPARECEU', 'Não compareceu')], default='AGENDADA', max_length=20)),
                ('observacoes_administrativas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas_criadas', to=settings.AUTH_USER_MODEL)),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to='especialidades.especialidade')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to='medicos.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to='pacientes.paciente')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas_alteradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('data', 'hora_inicio'),
                'indexes': [models.Index(fields=['medico', 'data', 'status'], name='consultas_c_medico__9555a8_idx'), models.Index(fields=['paciente', 'data', 'status'], name='consultas_c_pacient_7872df_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('hora_fim__gt', models.F('hora_inicio'))), name='consulta_horas_validas')],
            },
        ),
    ]
